//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetGroomingManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comm_Pet
    {
        public int SN { get; set; }
        public int customerSN { get; set; }
        public string petName { get; set; }
        public bool petGender { get; set; }
        public bool isState { get; set; }
        public int kindSN { get; set; }
        public int varietySN { get; set; }
        public string petRemark { get; set; }
    }
}
