//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetGroomingManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comm_Cosmetology> Comm_Cosmetology { get; set; }
        public virtual DbSet<Comm_Customer> Comm_Customer { get; set; }
        public virtual DbSet<Comm_Kind> Comm_Kind { get; set; }
        public virtual DbSet<Comm_Log> Comm_Log { get; set; }
        public virtual DbSet<Comm_Pet> Comm_Pet { get; set; }
        public virtual DbSet<Comm_Variety> Comm_Variety { get; set; }
        public virtual DbSet<Vw_Log> Vw_Log { get; set; }
        public virtual DbSet<Vw_Pet> Vw_Pet { get; set; }
    }
}
