//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetGroomingManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Pet
    {
        public int petSN { get; set; }
        public string petName { get; set; }
        public bool petGender { get; set; }
        public bool isState { get; set; }
        public string petRemark { get; set; }
        public Nullable<int> customerSN { get; set; }
        public string customerName { get; set; }
        public string phone { get; set; }
        public Nullable<int> kindSN { get; set; }
        public string kindName { get; set; }
        public Nullable<int> varietySN { get; set; }
        public string varietyName { get; set; }
    }
}
